version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.netty:netty-resolver-dns-native-macos
    versions:
    - 4.1.63.Final
  - dependency-name: io.netty:netty-resolver-dns
    versions:
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-dns
    versions:
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-unix-common
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-kqueue
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-epoll
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-resolver
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-handler-proxy
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-socks
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-http2
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-buffer
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.3
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.38.0
