name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run checks
        run: ./gradlew check
      - name: Run functional tests
        run: ./gradlew functional
        env:
          BLOB_ROUTER_URL: "http://reform-scan-blob-router-aat.service.core-compute-aat.internal"
          PROCESSOR_URL: "http://bulk-scan-processor-aat.service.core-compute-aat.internal"
          STORAGE_ACCOUNT_URL: "https://reformscan.aat.platform.hmcts.net"
          SIGNING_KEY_DER_BASE64:  ${{ secrets.SIGNING_KEY_DER_BASE64 }}
